$removedWinCaps = @( # add comments to keep cap

    "App.StepsRecorder"
    "Browser.InternetExplorer"
    "Hello.Face.20134"
    #"Language.Basic"
    "Language.Handwriting"
    "Language.OCR"
    "Language.Speech"
    "Language.TextToSpeech"
    "MathRecognizer"
    "Media.WindowsMediaPlayer"
    "Microsoft.Wallpapers.Extended"
    #"Microsoft.Windows.Notepad.System"
    "Microsoft.Windows.PowerShell.ISE"
    "Microsoft.Windows.WordPad"
    "OneCoreUAP.OneSync"
    #"OpenSSH.Client"
    #"OpenSSH.Server"
    "Print.Management.Console"

)

$winCaps = Get-WindowsCapability -Online

foreach ($cap in $removedWinCaps) {
    $winCaps | Where-Object -Property Name -like "$cap*" | Remove-WindowsCapability -Online
}

####################
#region AppXPackages

$removedAppxPackages = @(

    "Microsoft.AAD.BrokerPlugin"
#    "Microsoft.AccountsControl"
#    "Microsoft.AsyncTextService"
#    "Microsoft.BioEnrollment"
#    "Microsoft.CredDialogHost"
#    "Microsoft.ECApp"
#    "Microsoft.LockApp"
    "Microsoft.MicrosoftEdgeDevToolsClient"
    "Microsoft.UI.Xaml.CBS"
#    "Microsoft.Win32WebViewHost"
#    "Microsoft.Windows.Apprep.ChxApp"
#    "Microsoft.Windows.AssignedAccessLockApp"
#    "Microsoft.Windows.CallingShellApp"
    "Microsoft.Windows.CapturePicker"
    "Microsoft.Windows.CloudExperienceHost"
#    "Microsoft.Windows.ContentDeliveryManager"
    "Microsoft.Windows.NarratorQuickStart"
#    "Microsoft.Windows.OOBENetworkCaptivePortal"
#    "Microsoft.Windows.OOBENetworkConnectionFlow"
    "Microsoft.Windows.ParentalControls"
    "Microsoft.Windows.PeopleExperienceHost"
    "Microsoft.Windows.PinningConfirmationDialog"
    "Microsoft.Windows.PrintQueueActionCenter"
#    "Microsoft.Windows.StartMenuExperienceHost"
    "Microsoft.Windows.XGpuEjectDialog"
    "Microsoft.XboxGameCallableUI"
#    "MicrosoftWindows.Client.Core"
#    "MicrosoftWindows.UndockedDevKit"
#    "NcsiUwpApp"
    "Windows.CBSPreview"
#    "windows.immersivecontrolpanel"
    "Windows.PrintDialog"
#    "Microsoft.549981C3F5F10"
#    "Microsoft.UI.Xaml.2.4"
#    "Microsoft.UI.Xaml.2.7"
#    "Microsoft.VCLibs.140.00"
#    "Microsoft.VCLibs.140.00.UWPDesktop"
#    "Microsoft.NET.Native.Runtime.2.2"
#    "Microsoft.NET.Native.Framework.2.2"
    "Clipchamp.Clipchamp"
    "Microsoft.BingNews"
    "Microsoft.BingWeather"
    "Microsoft.DesktopAppInstaller"
    "Microsoft.GamingApp"
    "Microsoft.GetHelp"
    "Microsoft.Getstarted"
    "Microsoft.HEIFImageExtension"
    "Microsoft.HEVCVideoExtension"
    "Microsoft.MicrosoftOfficeHub"
    "Microsoft.MicrosoftSolitaireCollection"
    "Microsoft.MicrosoftStickyNotes"
    "Microsoft.People"
    "Microsoft.PowerAutomateDesktop"
    "Microsoft.RawImageExtension"
    "Microsoft.ScreenSketch"
    "Microsoft.StorePurchaseApp"
    "Microsoft.Todos"
    "Microsoft.VP9VideoExtensions"
    "Microsoft.WebMediaExtensions"
#    "Microsoft.WebpImageExtension"
    "Microsoft.WindowsAlarms"
    "Microsoft.WindowsCalculator"
    "Microsoft.WindowsCamera"
    "microsoft.windowscommunicationsapps"
    "Microsoft.WindowsFeedbackHub"
    "Microsoft.WindowsMaps"
#    "Microsoft.WindowsNotepad"
    "Microsoft.WindowsSoundRecorder"
#    "Microsoft.WindowsTerminal"
    "Microsoft.Xbox.TCUI"
    "Microsoft.XboxGameOverlay"
    "Microsoft.XboxGamingOverlay"
    "Microsoft.XboxIdentityProvider"
    "Microsoft.XboxSpeechToTextOverlay"
    "Microsoft.YourPhone"
    "MicrosoftCorporationII.QuickAssist"
    "MicrosoftTeams"
#    "Microsoft.MicrosoftEdge.Stable"
#    "Microsoft.NET.Native.Runtime.2.1"
#    "Microsoft.NET.Native.Runtime.2.1"
#    "Microsoft.NET.Native.Framework.2.1"
#    "Microsoft.NET.Native.Framework.2.1"
#    "Microsoft.VCLibs.140.00"
#    "AppUp.ThunderboltControlCenter"
#    "Microsoft.NET.Native.Runtime.2.2"
#    "Microsoft.NET.Native.Framework.2.2"
#    "AppUp.IntelGraphicsExperience"
#    "Microsoft.SecHealthUI"
#    "Microsoft.MicrosoftEdge"
    "Microsoft.UI.Xaml.CBS"
    "Microsoft.Windows.SecureAssessmentBrowser"
#    "Microsoft.Windows.ShellExperienceHost"
    "MicrosoftWindows.Client.CBS"
#    "MicrosoftWindows.Client.Core"
#    "Microsoft.UI.Xaml.2.7"
#    "Microsoft.UI.Xaml.2.7"
#    "Microsoft.Services.Store.Engagement"
#    "Microsoft.Services.Store.Engagement"
#    "Microsoft.VCLibs.140.00.UWPDesktop"
#    "Microsoft.WindowsStore"
#    "Microsoft.Windows.Photos"
#    "MicrosoftWindows.Client.WebExperience"
#    "Microsoft.UI.Xaml.2.8"
#    "Microsoft.UI.Xaml.2.8"
#    "Microsoft.Paint"
    "Microsoft.ZuneMusic"
    "Microsoft.ZuneVideo"
#    "Microsoft.WindowsAppRuntime.1.2"
#    "Microsoft.WindowsAppRuntime.1.2"
    "SpotifyAB.SpotifyMusic"
)

$installedAppxPackages = Get-AppxPackage -AllUsers | Where-Object -Property PackageUserInformation -match "Installed"

foreach ($app in $removedAppxPackages) {
    $installedAppxPackages | Where-Object {($_.Name -eq "$app") -and ($_.Nonremovable -eq $false) } | Remove-AppxPackage -AllUsers -verbose
}

$appxProvisionedPackages = Get-AppxProvisionedPackage -Online

foreach ($app in $removedAppxPackages) {
    $appxProvisionedPackages | Where-Object DisplayName -eq "$app" | Remove-AppxProvisionedPackage -Online -AllUsers
}

#endregion AppXPackages