$RequiredFeatures = @(
    "NET-Framework-45-Features"
    "Server-Media-Foundation"
    "RPC-over-HTTP-proxy"
    "RSAT-Clustering"
    "RSAT-Clustering-CmdInterface"
    "RSAT-Clustering-Mgmt"
    "RSAT-Clustering-PowerShell"
    "WAS-Process-Model"
    "Web-Asp-Net45"
    "Web-Basic-Auth"
    "Web-Client-Auth"
    "Web-Digest-Auth"
    "Web-Dir-Browsing"
    "Web-Dyn-Compression"
    "Web-Http-Errors"
    "Web-Http-Logging"
    "Web-Http-Redirect"
    "Web-Http-Tracing"
    "Web-ISAPI-Ext"
    "Web-ISAPI-Filter"
    "Web-Lgcy-Mgmt-Console"
    "Web-Metabase"
    "Web-Mgmt-Console"
    "Web-Mgmt-Service"
    "Web-Net-Ext45"
    "Web-Request-Monitor"
    "Web-Server"
    "Web-Stat-Compression"
    "Web-Static-Content"
    "Web-Windows-Auth"
    "Web-WMI"
    "Windows-Identity-Foundation"
    "RSAT-ADDS"
)

Install-WindowsFeature $RequiredFeatures


$dotnet48url = "https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe"
Start-BitsTransfer $dotnet48url