#

- name: Add EPEL repository
  ansible.builtin.yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Add ZFS repository
  ansible.builtin.yum_repository:
    name: zfs
    description: ZFS on Linux for EL9 - dkms
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/